name: 🐛 Bug Report
description: Signaler un bug
title: "[BUG] "
labels: ["type:bug", "status:needs-triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: 📱 Composant
      options:
        - API Backend
        - Web Dashboard
        - Mobile App
        - Admin Panel
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Description du bug
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 🔄 Étapes de reproduction
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true
